### ISSUE TITLE
AttributeError: module 'typing' has no attribute 'AsyncGenerator'

### ISSUE THREAD

**Issue by foxmask** [encode/databases#110]
after installing databases + sqlite by
```
 pip install databases[sqlite]
Requirement already satisfied: databases[sqlite] in /home/foxmask/DjangoVirtualEnv/yo/lib/python3.6/site-packages (0.2.2)
Requirement already satisfied: sqlalchemy in /home/foxmask/DjangoVirtualEnv/yo/lib/python3.6/site-packages (from databases[sqlite]) (1.3.5)
Requirement already satisfied: aiocontextvars; python_version < "3.7" in /home/foxmask/DjangoVirtualEnv/yo/lib/python3.6/site-packages (from databases[sqlite]) (0.2.2)
Collecting aiosqlite; extra == "sqlite" (from databases[sqlite])
  Downloading https://files.pythonhosted.org/packages/74/bb/f5796f90ba82e788339449eb239dbb875ac072f6842f4429bcb76b877bc9/aiosqlite-0.10.0.tar.gz
Requirement already satisfied: contextvars==2.4; python_version < "3.7" in /home/foxmask/DjangoVirtualEnv/yo/lib/python3.6/site-packages (from aiocontextvars; python_version < "3.7"->databases[sqlite]) (2.4)
Requirement already satisfied: immutables>=0.9 in /home/foxmask/DjangoVirtualEnv/yo/lib/python3.6/site-packages (from contextvars==2.4; python_version < "3.7"->aiocontextvars; python_version < "3.7"->databases[sqlite]) (0.9)
Building wheels for collected packages: aiosqlite
  Building wheel for aiosqlite (setup.py) ... done
  Stored in directory: /home/foxmask/.cache/pip/wheels/58/ca/ba/6e4dc3703d0ec04af6b602034bbd99b96f7ecb4b22ef93a641
Successfully built aiosqlite
Installing collected packages: aiosqlite
Successfully installed aiosqlite-0.10.0
```
get the following errors
```
 $ python 
Python 3.6.0 (default, Dec 27 2016, 09:15:23) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import databases
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/foxmask/DjangoVirtualEnv/yo/lib/python3.6/site-packages/databases/__init__.py", line 1, in <module>
    from databases.core import Database, DatabaseURL
  File "/home/foxmask/DjangoVirtualEnv/yo/lib/python3.6/site-packages/databases/core.py", line 12, in <module>
    from databases.interfaces import ConnectionBackend, DatabaseBackend, TransactionBackend
  File "/home/foxmask/DjangoVirtualEnv/yo/lib/python3.6/site-packages/databases/interfaces.py", line 17, in <module>
    class ConnectionBackend:
  File "/home/foxmask/DjangoVirtualEnv/yo/lib/python3.6/site-packages/databases/interfaces.py", line 38, in ConnectionBackend
    ) -> typing.AsyncGenerator[typing.Mapping, None]:
AttributeError: module 'typing' has no attribute 'AsyncGenerator'
```

**Comment by tomchristie** [comment]
Python lists `typing.AsyncGenerator` as "New in version 3.6.1.".

https://docs.python.org/3/library/typing.html#typing.AsyncGenerator

We can either deal with this in a "compat" module, or else explicitly specify 3.6.1+

**Comment by foxmask** [comment]
I see, thanks

**Comment by foxmask** [comment]
it's ok with python 3.6.8

**Comment by ProsperousHeart** [comment]
> Python lists `typing.AsyncGenerator` as "New in version 3.6.1.".
> 
> https://docs.python.org/3/library/typing.html#typing.AsyncGenerator
> 
> We can either deal with this in a "compat" module, or else explicitly specify 3.6.1+

If you are on 3.6.0 or earlier, it will fail. This comment above made me realize I had to upgrade python to 3.6.1. and it resolved this issue for me.
