### ISSUE TITLE
Password containing digits and hashmark cannot be used (MySQL)

### ISSUE THREAD

**Issue by rkrell** [encode/databases#269]
`databases==0.4.1`

If using a URL like:

`mysql://user_name:Xx7#4xxXX77xx@localhost/db_name`

I get the following error:

```
ERROR:    Traceback (most recent call last):
  File "/home/rkrell/work/lib/python3.7/site-packages/starlette/routing.py", line 526, in lifespan
    async for item in self.lifespan_context(app):
  File "/home/rkrell/work/lib/python3.7/site-packages/starlette/routing.py", line 467, in default_lifespan
    await self.startup()
  File "/home/rkrell/work/lib/python3.7/site-packages/starlette/routing.py", line 502, in startup
    await handler()
  File "./main.py", line 154, in startup
    await database.connect()
  File "/home/rkrell/work/lib/python3.7/site-packages/databases/core.py", line 84, in connect
    await self._backend.connect()
  File "/home/rkrell/work/lib/python3.7/site-packages/databases/backends/mysql.py", line 63, in connect
    port=self._database_url.port or 3306,
  File "/home/rkrell/work/lib/python3.7/site-packages/databases/core.py", line 448, in port
    return self.components.port
  File "/usr/lib/python3.7/urllib/parse.py", line 169, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'Xx7'
```

**Comment by rkrell** [comment]
Found a workaround by escaping the hashmark (`%23` instead of `#`):
`mysql://user_name:Xx7%234xxXX77xx@localhost/db_name`

**Comment by rkrell** [comment]
This workaround is probably the intended way of dealing with hash marks in URLs.
