### ISSUE TITLE
SQLAlchemy generate_series raises: invalid input for query argument $1: '1 month' ('str' object has no attribute 'days')

### ISSUE THREAD

**Issue by Feijo** [encode/databases#316]
`databases==0.4.3`
`asyncpg==0.21.0`
`SQLAlchemy==1.3.22`

When using SQLAlchemy's `func.generate_series` with a `string`, it raises an exception.

**Demo using Databases**
```
import asyncio
from datetime import datetime
from databases import Database
from sqlalchemy import DATE, cast, column, func, select, literal

database = Database('postgresql://postgres:postgres@localhost/new_db')

async def run():
    await database.connect()

    series = func.generate_series(cast(datetime(2000, 1, 1), DATE), cast(datetime(2001, 1, 1), DATE), '1 month').alias('month')
    query = select([column('month')]).select_from(series)

    await database.fetch_all(query)

    await database.disconnect()

loop = asyncio.get_event_loop()
loop.run_until_complete(run())
```

**Exception**

```
Traceback (most recent call last):
  File "asyncpg\protocol\prepared_stmt.pyx", line 146, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
  File "asyncpg\protocol\codecs/base.pyx", line 192, in asyncpg.protocol.protocol.Codec.encode
  File "asyncpg\protocol\codecs/base.pyx", line 103, in asyncpg.protocol.protocol.Codec.encode_scalar
  File "asyncpg\pgproto\./codecs/datetime.pyx", line 362, in asyncpg.pgproto.pgproto.interval_encode
AttributeError: 'str' object has no attribute 'days'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 19, in <module>
    loop.run_until_complete(run())
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "test.py", line 14, in run
    await database.fetch_all(query)
  File "C:\Program Files\Python38\lib\site-packages\databases\core.py", line 140, in fetch_all
    return await connection.fetch_all(query, values)
  File "C:\Program Files\Python38\lib\site-packages\databases\core.py", line 239, in fetch_all
    return await self._connection.fetch_all(built_query)
  File "C:\Program Files\Python38\lib\site-packages\databases\backends\postgres.py", line 153, in fetch_all
    rows = await self._connection.fetch(query, *args)
  File "C:\Program Files\Python38\lib\site-packages\asyncpg\connection.py", line 443, in fetch
    return await self._execute(query, args, 0, timeout)
  File "C:\Program Files\Python38\lib\site-packages\asyncpg\connection.py", line 1445, in _execute
    result, _ = await self.__execute(
  File "C:\Program Files\Python38\lib\site-packages\asyncpg\connection.py", line 1454, in __execute
    return await self._do_execute(query, executor, timeout)
  File "C:\Program Files\Python38\lib\site-packages\asyncpg\connection.py", line 1476, in _do_execute
    result = await executor(stmt, None)
  File "asyncpg\protocol\protocol.pyx", line 178, in bind_execute
  File "asyncpg\protocol\prepared_stmt.pyx", line 160, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
asyncpg.exceptions.DataError: invalid input for query argument $1: '1 month' ('str' object has no attribute 'days')
```

**Demo using SQLAlchemy's sync API (work's fine)**
```
from datetime import datetime
from sqlalchemy import DATE, cast, column, create_engine, func, select

engine = create_engine('postgresql://postgres:postgres@localhost/new_db', echo=True)

series = func.generate_series(cast(datetime(2000, 1, 1), DATE), cast(datetime(2001, 1, 1), DATE), '1 month').alias('month')
query = select([column('month')]).select_from(series)

print(engine.connect().execute(query).fetchall())
```

**Output**

```
2021-03-28 00:38:36,331 INFO sqlalchemy.engine.base.Engine SELECT month
FROM generate_series(CAST(%(param_1)s AS DATE), CAST(%(param_2)s AS DATE), %(generate_series_1)s) AS month
2021-03-28 00:38:36,331 INFO sqlalchemy.engine.base.Engine {'param_1': datetime.datetime(2000, 1, 1, 0, 0), 'param_2': datetime.datetime(2001, 1, 1, 0, 0), 'generate_series_1': '1 month'}
[(datetime.datetime(2000, 1, 1, 0, 0, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=780, name=None)),), (datetime.datetime(2000, 2, 1, 0, 0, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=780, name=None)),), (datetime.datetime(2000, 3, 1, 0, 0, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=780, name=None)),), (datetime.datetime(2000, 4, 1, 0, 0, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=720, name=None)),), (datetime.datetime(2000, 5, 1, 0, 0, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=720, name=None)),), (datetime.datetime(2000, 6, 1, 0, 0, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=720, name=None)),), (datetime.datetime(2000, 7, 1, 0, 0, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=720, name=None)),), (datetime.datetime(2000, 8, 1, 0, 0, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=720, name=None)),), (datetime.datetime(2000, 9, 1, 0, 0, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=720, name=None)),), (datetime.datetime(2000, 10, 1, 0, 0, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=720, name=None)),), (datetime.datetime(2000, 11, 1, 0, 0, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=780, name=None)),), (datetime.datetime(2000, 12, 1, 0, 0, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=780, name=None)),), (datetime.datetime(2001, 1, 1, 0, 0, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=780, name=None)),)]
```

With the async api it only works if I use `timedelta` instead of a `string`, however `timedelta(months=1)` does not exist.

**Comment by Feijo** [comment]
It was a problem with asyncpg. This is how I fixed it:
https://github.com/MagicStack/asyncpg/issues/728
