### ISSUE TITLE
broken installation instructions for non-default db drivers

### ISSUE THREAD

**Issue by chrono** [encode/databases#429]
Via readme.md:
```
You can also use other database drivers supported by databases:

$ pip install databases[postgresql+aiopg]
$ pip install databases[mysql+asyncmy]
```

Is there any python/pip combination for which this works? I swear I've seen the same plus notation before somewhere but I'm pretty sure it doesn't work:

```
docker run --rm python:3.9 bash -exc "pip install -U pip==21.3.1; pip install 'databases[postgresql+aiopg]'"

+ pip install -U pip==21.3.1
Collecting pip==21.3.1
  Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.2.4
    Uninstalling pip-21.2.4:
      Successfully uninstalled pip-21.2.4
Successfully installed pip-21.3.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
+ pip install 'databases[postgresql+aiopg]'
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/packaging/requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyparsing.py", line 1955, in parseString
    raise exc
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyparsing.py", line 3814, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd, found '['  (at char 11), (line:1, col:12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 305, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 380, in get_requirements
    req_to_add = install_req_from_line(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/req/constructors.py", line 366, in install_req_from_line
    parts = parse_req_from_line(name, line_source)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/req/constructors.py", line 306, in parse_req_from_line
    extras = convert_extras(extras_as_string)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/req/constructors.py", line 58, in convert_extras
    return get_requirement("placeholder" + extras.lower()).extras
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/utils/packaging.py", line 84, in get_requirement
    return Requirement(req_string)
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/packaging/requirements.py", line 104, in __init__
    raise InvalidRequirement(
pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "'[postgre'": Expected stringEnd
```

**Comment by aminalaee** [comment]
Thanks for reporting this.
As far as I remember it should've worked on Bash, but not on ZSH (default macOS).

I think it will be picked up when we remove default database drivers in #421 .

After that we will have something like:

```shell
pip install databases[asyncpg]
pip install databases[aiopg]
...
```
