### ISSUE TITLE
Transaction and gather

### ISSUE THREAD

**Issue by kitqee** [encode/databases#573]
It should commit, but I get the error. If you remove the exception or run only f1 in gather or run gather(f2, f1) it will work.
What is wrong? 

OS: macos
python version: 3.11
databases version: 0.8.0
database backend: postgresql 
database driver: asyncpg 

```
database = Database('postgresql+asyncpg://name:password@127.0.0.1:5432/db')

async def f1(connection):
    await connection.execute("SELECT pg_backend_pid();")
    raise ValueError('oh')

async def f2(connection):
    await connection.execute("SELECT pg_backend_pid();")

@database.transaction()
async def f3():
    connection = database.connection()
    try:
        await asyncio.gather(f1(connection), f2(connection))
    except ValueError:
        pass

async def main():
    await database.connect()
    await f3()

asyncio.run(main())
```

```
Traceback (most recent call last):
  File "/Users/sshanov/Projects/discord/src/db.py", line 42, in <module>
    asyncio.run(main())
  File "/Users/sshanov/.pyenv/versions/3.11.4/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/sshanov/.pyenv/versions/3.11.4/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sshanov/.pyenv/versions/3.11.4/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/sshanov/Projects/discord/src/db.py", line 39, in main
    await f3()
  File "/Users/sshanov/.pyenv/versions/any/lib/python3.11/site-packages/databases/core.py", line 443, in wrapper
    async with self:
  File "/Users/sshanov/.pyenv/versions/any/lib/python3.11/site-packages/databases/core.py", line 428, in __aexit__
    await self.commit()
  File "/Users/sshanov/.pyenv/versions/any/lib/python3.11/site-packages/databases/core.py", line 465, in commit
    await self._transaction.commit()
  File "/Users/sshanov/.pyenv/versions/any/lib/python3.11/site-packages/databases/backends/postgres.py", line 319, in commit
    await self._transaction.commit()
  File "/Users/sshanov/.pyenv/versions/any/lib/python3.11/site-packages/asyncpg/transaction.py", line 219, in commit
    await self.__commit()
  File "/Users/sshanov/.pyenv/versions/any/lib/python3.11/site-packages/asyncpg/transaction.py", line 187, in __commit
    await self._connection.execute(query)
  File "/Users/sshanov/.pyenv/versions/any/lib/python3.11/site-packages/asyncpg/connection.py", line 317, in execute
    return await self._protocol.query(query, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 323, in query
  File "asyncpg/protocol/protocol.pyx", line 707, in asyncpg.protocol.protocol.BaseProtocol._check_state
asyncpg.exceptions._base.InterfaceError: cannot perform operation: another operation is in progress
```

**Comment by zanieb** [comment]
I'm not sure, but it looks like `f3` is attempting to commit the transaction due to the error and `f2` is still running. Maybe use `gather(..., return_exceptions=True)` instead of catching the exception?

**Comment by kitqee** [comment]
Looks like you are right and it helped. 
Thanks!
